In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

In [8]:
df=pd.read_csv('cardekho_imputated.csv',index_col=[0])

In [9]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [10]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [11]:
df.drop(['car_name','brand'],axis=1,inplace=True)

In [12]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [13]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

Getting the different type of features.

In [15]:
num_feature=[feature for feature in df.columns if df[feature].dtype!='O']
print('Number of numerical features are:',len(num_feature))

Number of numerical features are: 7

In [17]:
cat_feature=[feature for feature in df.columns if df[feature].dtype=='O']
print('The number of categorical features are:',len(cat_feature))

The number of categorical features are: 4

In [20]:
discrete_feature=[feature for feature in num_feature if len(df[feature].unique())<=25]
print('Number of discrete_features are:',len(discrete_feature))

Number of discrete_features are: 2

In [21]:
continous_feature=[feature for feature in  num_feature if feature not in discrete_feature]
print('The number of Continous features are:',len(continous_feature))

The number of Continous features are: 5

TRAIN_TEST_SPLIT

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X=df.drop('selling_price',axis=1)

In [24]:
y=df['selling_price']

In [25]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [26]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [27]:
len(df['model'].unique())

120

In [29]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X['model']=le.fit_transform(X['model'])

In [30]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [31]:
len(df['seller_type'].unique())

3

In [33]:
len(df['fuel_type'].unique())

5

In [34]:
len(df['transmission_type'].unique())

2

Since the number of category above are very very less like 3 5 2 compare to 190 or 200 so here we will be doing onehot encoding rather than labelencoding but for high number of categories we will do labelled encoding.

In [42]:
num_features=X.select_dtypes(exclude="object").columns

In [43]:
onehot_columns=['seller_type','fuel_type','transmission_type']

In [44]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [46]:
from sklearn.compose import ColumnTransformer

In [47]:
num_transformer=StandardScaler()

In [49]:
oh_transformer=OneHotEncoder(drop='first')

In [52]:
preprocessor=ColumnTransformer(
    [
("OneHotEncoder",oh_transformer,onehot_columns),
("StandardScaler",num_transformer,num_features)
],remainder='passthrough'
)

In [53]:
X=preprocessor.fit_transform(X)

In [56]:
X

array([[ 1.        ,  0.        ,  0.        , ..., -1.32425883,
        -1.26335238, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43257082, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.47911321, -0.40302241],
       ...,
       [ 0.        ,  0.        ,  1.        , ...,  0.02291783,
         0.06822523, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  1.32979434,
         0.91715831,  2.07344426],
       [ 0.        ,  0.        ,  0.        , ...,  0.02099878,
         0.39588361, -0.40302241]])

In [57]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [65]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [66]:
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=np.sqrt(mse)
    r2_square=r2_score(true,predicted)
    return mae,rmse,r2_square

In [85]:
models={
    "LinearRegression":LinearRegression(),
    "Lasso":Lasso(),
    "Ridge":Ridge(),
"K-Neighbors Regressor":KNeighborsRegressor(),
"Decision Tree":DecisionTreeRegressor(),
"Random Forest Regressor":RandomForestRegressor(),
    
}
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    y_train_predict=model.predict(X_train)
    y_test_predict=model.predict(X_test)

    model_train_mae,model_train_rmse,model_train_r2=evaluate_model(y_train,y_train_predict)
    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_test,y_test_predict)

    print(list(models.keys())[i])

    print('Model performance for the training set:')
    print("-Root Mean Squared error:{:.4f}".format (model_train_rmse))
    print("-Mean Absolute error:{:.4f}".format (model_train_mae))
    print("-R2:{:.4f}".format (model_train_r2))

    print("--------------------------------------")

    print('Model performance for the testing set:')
    print("-Root Mean Squared error:{:.4f}".format (model_test_rmse))
    print("-Mean Absolute error:{:.4f}".format (model_test_mae))
    print("-R2:{:.4f}".format (model_test_r2))

    print('='*35)
    print('\n')

LinearRegression
Model performance for the training set:
-Root Mean Squared error:553855.6665
-Mean Absolute error:268101.6071
-R2:0.6218
--------------------------------------
Model performance for the testing set:
-Root Mean Squared error:502543.5930
-Mean Absolute error:279618.5794
-R2:0.6645
===================================


Lasso
Model performance for the training set:
-Root Mean Squared error:553855.6710
-Mean Absolute error:268099.2226
-R2:0.6218
--------------------------------------
Model performance for the testing set:
-Root Mean Squared error:502542.6696
-Mean Absolute error:279614.7461
-R2:0.6645
===================================


Ridge
Model performance for the training set:
-Root Mean Squared error:553856.3160
-Mean Absolute error:268059.8015
-R2:0.6218
--------------------------------------
Model performance for the testing set:
-Root Mean Squared error:502533.8230
-Mean Absolute error:279557.2169
-R2:0.6645
===================================


K-Neighbors Regressor
Model performance for the training set:
-Root Mean Squared error:325873.0088
-Mean Absolute error:91425.4705
-R2:0.8691
--------------------------------------
Model performance for the testing set:
-Root Mean Squared error:253024.3951
-Mean Absolute error:112526.3461
-R2:0.9150
===================================


Decision Tree
Model performance for the training set:
-Root Mean Squared error:20797.2352
-Mean Absolute error:5164.8199
-R2:0.9995
--------------------------------------
Model performance for the testing set:
-Root Mean Squared error:303093.4343
-Mean Absolute error:125329.0815
-R2:0.8780
===================================


Random Forest Regressor
Model performance for the training set:
-Root Mean Squared error:120680.0070
-Mean Absolute error:39883.7136
-R2:0.9820
--------------------------------------
Model performance for the testing set:
-Root Mean Squared error:229280.3456
-Mean Absolute error:101504.3740
-R2:0.9302
===================================

HYPER-PARAMETER-TUNING

In [108]:
knn_params={"n_neighbors":[2,3,10,20,40,50]}
rf_params={"max_depth":[5,8,15,None,10],
           "max_features":[5,7,"auto",8],
           "min_samples_split":[2,8,15,20],
           "n_estimators":[100,200,500,1000]}

In [109]:
randomcv_models=[('KNN',KNeighborsRegressor(),knn_params),
                ('RF',RandomForestRegressor(),rf_params)
                ]

In [110]:
from sklearn.model_selection import RandomizedSearchCV


model_params = {}
for name, model, params in randomcv_models:
 
    random = RandomizedSearchCV(estimator=model,
                               param_distributions=params,
                               n_iter=100,
                               cv=3,
                               verbose=2,
                               n_jobs=-1)
    random.fit(X_train, y_train)
    model_params[name] = random.best_params_

for model_name in model_params:
    print(f"---------------Best params for {model_name}---------------")
    print(model_params[model_name])
    print()

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
---------------Best params for KNN---------------
{'n_neighbors': 10}

---------------Best params for RF---------------
{'n_estimators': 100, 'min_samples_split': 2, 'max_features': 8, 'max_depth': 15}

In [113]:
models={
    "K-Neighbors Regressor": KNeighborsRegressor(n_neighbors=10, n_jobs=-1),
    "Random Forest Regressor": RandomForestRegressor(n_estimators=100, min_samples_split=2, max_features=8, max_depth=15, n_jobs=-1),   
}
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
    y_train_predict = model.predict(X_train)
    y_test_predict = model.predict(X_test)

    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_predict)
    model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_predict)

    print(list(models.keys())[i])

    print('Model performance for the training set:')
    print("-Root Mean Squared error:{:.4f}".format(model_train_rmse))
    print("-Mean Absolute error:{:.4f}".format(model_train_mae))
    print("-R2:{:.4f}".format(model_train_r2))

    print("--------------------------------------")

    print('Model performance for the testing set:')
    print("-Root Mean Squared error:{:.4f}".format(model_test_rmse))
    print("-Mean Absolute error:{:.4f}".format(model_test_mae))
    print("-R2:{:.4f}".format(model_test_r2))

    print('='*35)
    print('\n')

K-Neighbors Regressor
Model performance for the training set:
-Root Mean Squared error:363460.7706
-Mean Absolute error:103472.0474
-R2:0.8371
--------------------------------------
Model performance for the testing set:
-Root Mean Squared error:263888.0623
-Mean Absolute error:117496.2131
-R2:0.9075
===================================


Random Forest Regressor
Model performance for the training set:
-Root Mean Squared error:148688.8199
-Mean Absolute error:54099.8802
-R2:0.9727
--------------------------------------
Model performance for the testing set:
-Root Mean Squared error:216675.9112
-Mean Absolute error:97649.3135
-R2:0.9376
===================================